-- AlterEnum: extend ScheduleIIIGroup to the full Schedule III (Division I) sub-head list.
-- Safe to recreate: FIXED_ASSETS (the only removed value) has zero rows referencing it.
BEGIN;
CREATE TYPE "ScheduleIIIGroup_new" AS ENUM ('SHARE_CAPITAL', 'RESERVES_AND_SURPLUS', 'SHARE_APPLICATION_MONEY', 'LONG_TERM_BORROWINGS', 'DEFERRED_TAX_LIABILITIES', 'OTHER_LONG_TERM_LIABILITIES', 'LONG_TERM_PROVISIONS', 'SHORT_TERM_BORROWINGS', 'TRADE_PAYABLES', 'OTHER_CURRENT_LIABILITIES', 'SHORT_TERM_PROVISIONS', 'TANGIBLE_ASSETS', 'INTANGIBLE_ASSETS', 'CAPITAL_WORK_IN_PROGRESS', 'INTANGIBLE_ASSETS_UNDER_DEVELOPMENT', 'NON_CURRENT_INVESTMENTS', 'DEFERRED_TAX_ASSETS', 'LONG_TERM_LOANS_AND_ADVANCES', 'OTHER_NON_CURRENT_ASSETS', 'CURRENT_INVESTMENTS', 'INVENTORIES', 'TRADE_RECEIVABLES', 'CASH_AND_CASH_EQUIVALENTS', 'SHORT_TERM_LOANS_AND_ADVANCES', 'OTHER_CURRENT_ASSETS', 'REVENUE_FROM_OPERATIONS', 'OTHER_INCOME', 'COST_OF_MATERIALS_CONSUMED', 'PURCHASES_OF_STOCK_IN_TRADE', 'CHANGES_IN_INVENTORIES', 'EMPLOYEE_BENEFIT_EXPENSE', 'FINANCE_COSTS', 'DEPRECIATION_AND_AMORTIZATION_EXPENSE', 'OTHER_EXPENSES', 'CURRENT_TAX_EXPENSE', 'DEFERRED_TAX_EXPENSE');
ALTER TABLE "accounts" ALTER COLUMN "schedule_iii_group" TYPE "ScheduleIIIGroup_new" USING ("schedule_iii_group"::text::"ScheduleIIIGroup_new");
ALTER TYPE "ScheduleIIIGroup" RENAME TO "ScheduleIIIGroup_old";
ALTER TYPE "ScheduleIIIGroup_new" RENAME TO "ScheduleIIIGroup";
DROP TYPE "ScheduleIIIGroup_old";
COMMIT;
